theme: jekyll-theme-architect
title: Welcome to the Chris KY FUNG's Homepage
description: Feel free to bookmark this to keep an eye on my project updates
timezone: HK
google_analytics: UA-72575541-9
permalink: /blog/:year/:month/:day/:title
paginate: 5
paginate_path: "/blog/page:num/"

gems:
  - jekyll-sitemap

image:
  background: https://scontent.xx.fbcdn.net/v/t1.0-9/19030395_1446916822036408_4482890102250202742_n.png?oh=74d595ba25a2af74100278a100cdb258&oe=599C7223
