theme: jekyll-theme-architect
title: Chris KY FUNG's GitHub Page
description: Feel free to bookmark this to keep an eye on my project updates
timezone: HK
google_analytics: UA-72575541-9
disqus: chriskyfung
permalink: /blog/:year/:month/:day/:title
paginate: 10
paginate_path: "/blog/page:num/"
site_url: https://chriskyfung.github.io/
excerpt_separator: "<!--more-->"
gems:
  - jekyll-sitemap
plugins:
  - jekyll-redirect-from